# Velocity Kinematics and Statics Assignment

In [1]:
import modern_robotics as mr
import numpy as np
import math
from numpy import linalg as la

1) A 3R planar open-chain robot is shown. Suppose the tip generates a wrench that can be expressed in the space frame {s} as a force of 2N in the $\hat{x_s}$ direction, with no component in the $\hat{y_s}$ direction and zero moment in the {s} frame. What torques is counterclokwise. Give the torque values in the form of (T1, T2, T3).<br><br>
<img src='img/Img14.jpg'>

In [2]:
Fs=np.array([[0,0,0,2,0,0]])
Fs=np.transpose(Fs)
#############################
S1=np.transpose(np.array([[0,0,1,0,0,0]]))
#############################
w2=np.array([0,0,1])
q2=np.array([1,0,0])
v2=np.cross(-w2,q2)
##############################
S2=np.transpose(np.array([[0,0,1,0,-1,0]]))
##############################
w3=np.array([0,0,1])
q3=np.array([2,0,0])
v3=np.cross(-w3,q3)
##############################
S3=np.transpose(np.array([[0,0,1,0,-2,0]]))

In [3]:
SList=np.array([[0,0,0],[0,0,0],[1,1,1],[0,0,0],[0,-1,-2],[0,0,0]])
print(SList)

[[ 0  0  0]
 [ 0  0  0]
 [ 1  1  1]
 [ 0  0  0]
 [ 0 -1 -2]
 [ 0  0  0]]


In [4]:
theta=np.array([0, math.pi/4, 0])
print(theta)

[0.         0.78539816 0.        ]


In [5]:
Js=mr.JacobianSpace(SList,theta)
print(Js)

[[ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 1.          1.          1.        ]
 [ 0.          0.          0.70710678]
 [ 0.         -1.         -1.70710678]
 [ 0.          0.          0.        ]]


In [6]:
T=np.dot(np.transpose(Js),Fs)
print(T)

[[0.        ]
 [0.        ]
 [1.41421356]]


2) The 4R planar open-chain robot has an end effectir frame {b} as its tip. Considering only the planar twist components $(w_{bz},v_{bx},v_{by})$ of the body twist $V_b$.<br><br>

<img src='img/Img15.jpg'>

<center>
    $J_b=\begin{vmatrix}
    1 & 1 & 1 & 1\\
    L_3S_4+L_2S_{34}+L_1S_{234} & L_3S_4+L_2S_{34} & L_3S_4 & 0\\
    L_4+L_3C_4+L_2C_{34}+L_1C_{234} & L_4+L_3C_4+L_2C_{34} & L_4+L_3C_4 & L_4 \end{vmatrix}$
</center>

Suppose L1=L2=L3=L4=1 and the chainis at the configuration $\theta_1=\theta_2=0,\; \theta_3=\pi/2\; and\; \theta_4=-\pi/2$. The joiints generate torques to create the wrench Fb=(0,0,10,10,10,0) at the last link. Where arte the torques at each of the joints?

In [7]:
Fb=np.transpose(np.array([[0,0,10,10,10,0]]))
Jb=np.array([[0,0,0,0],[0,0,0,0],[1,1,1,1],[-1,-1,-1,0],[3,2,1,1],[0,0,0,0]])
print(Jb)

[[ 0  0  0  0]
 [ 0  0  0  0]
 [ 1  1  1  1]
 [-1 -1 -1  0]
 [ 3  2  1  1]
 [ 0  0  0  0]]


In [8]:
T=np.dot(np.transpose(Jb),Fb)
print(T)

[[30]
 [20]
 [10]
 [20]]


3) The RRP is shown below in its zero position, find Js and Jb <br><br>
<img src='img/Img17.png'>

In [9]:
SList=np.array([[0,1,0],[0,0,0],[1,0,0],[0,0,0],[0,2,1],[0,0,0]])
Theta=np.array([math.pi/2,math.pi/2,1])
Js=mr.JacobianSpace(SList,Theta)
print(np.round(Js,2))

[[ 0.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0. -2. -0.]
 [ 0.  0.  0.]
 [ 0.  0.  1.]]


In [10]:
BList=np.array([[0,-1,0],[1,0,0],[0,0,0],[3,0,0],[0,3,0],[0,0,1]])
Theta=np.array([math.pi/2,math.pi/2,1])
Jb=mr.JacobianBody(BList,Theta)
print(np.round(Jb,2))

[[ 0. -1.  0.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  4.  0.]
 [ 0.  0.  1.]]


4) The Kinematic of the 7R WAM robot are given in section 4.1.3. The numerical Jb when all joint angles are $\pi/2$ is:

In [11]:
Jb=np.array([[0,-1,0,0,-1,0,0],[0,0,1,0,0,1,0],[1,0,0,1,0,0,1],[-0.105,0,0.006,-0.045,0,0.006,0],[-0.889,0.006,0,-0.844,0.006,0,0],[0,-0.105,0.889,0,0,0,0]])
print(Jb)

[[ 0.    -1.     0.     0.    -1.     0.     0.   ]
 [ 0.     0.     1.     0.     0.     1.     0.   ]
 [ 1.     0.     0.     1.     0.     0.     1.   ]
 [-0.105  0.     0.006 -0.045  0.     0.006  0.   ]
 [-0.889  0.006  0.    -0.844  0.006  0.     0.   ]
 [ 0.    -0.105  0.889  0.     0.     0.     0.   ]]


Extract the linear velocity portion Jv. Calculate the directions and lengths of the principal semi-axes of the 3D linear velocity manipulability ellipsoid based on Jv. Give a unit vector to represent the direction of the longest principal semi-axes

In [12]:
Jv=Jb[3:]
print(Jv)

[[-0.105  0.     0.006 -0.045  0.     0.006  0.   ]
 [-0.889  0.006  0.    -0.844  0.006  0.     0.   ]
 [ 0.    -0.105  0.889  0.     0.     0.     0.   ]]


In [13]:
A=np.dot(Jv,Jv.T)
print(A)

[[ 1.312200e-02  1.313250e-01  5.334000e-03]
 [ 1.313250e-01  1.502729e+00 -6.300000e-04]
 [ 5.334000e-03 -6.300000e-04  8.013460e-01]]


In [14]:
w,v=la.eig(A)
print(np.round(w,3))
print()
print(np.round(v.T,3))

[0.002 1.514 0.801]

[[-0.996  0.087  0.007]
 [ 0.087  0.996 -0.   ]
 [ 0.007 -0.     1.   ]]
