# Forward Kinematics Assignment

In [1]:
import numpy as np
import modern_robotics as mr
import math
pi=math.pi

1) The URRRR spatial open chain robot is on its 0-position. For L=1 determine the end-effector zero configuration M. 
<br>
<img src='img/img4.jpg'>

In [2]:
M=np.array([[1,0,0,3.73],[0,1,0,0],[0,0,1,2.73],[0,0,0,1]])
print(M)

[[1.   0.   0.   3.73]
 [0.   1.   0.   0.  ]
 [0.   0.   1.   2.73]
 [0.   0.   0.   1.  ]]


2) Determine the screw axes Si

In [3]:
w1=np.array([0,0,1])
q1=np.array([1,0,0])
v1=np.cross(-w1,q1)
#_____________________________#
w2=np.array([0,1,0])
q2=np.array([1,0,0])
v2=np.cross(-w2,q2)
#_____________________________#
w3=np.array([0,1,0])
q3=np.array([2.73,0,-1])
v3=np.cross(-w3,q3)
#_____________________________#
w4=np.array([0,1,0])
q4=np.array([3.73,0,0.73])
v4=np.cross(-w4,q4)
#_____________________________#
w5=np.array([0,0,0])
v5=np.array([0,0,1])
#_____________________________#
w6=np.array([0,0,1])
q6=np.array([3.73,0,2.73])
v6=np.cross(-w6,q6)
#_____________________________#
print('v1: {}\nv2: {}\nv3: {}\nv4: {}\nv5: {}\nv6: {}'.format(v1, v2, v3, v4, v5, v6))

v1: [ 0 -1  0]
v2: [0 0 1]
v3: [1.   0.   2.73]
v4: [-0.73  0.    3.73]
v5: [0 0 1]
v6: [ 0.   -3.73  0.  ]


In [4]:
SList=np.array([[0,0,0,0,0,0],[0,1,1,1,0,0],[1,0,0,0,0,1],[0,0,1,-0.73,0,0],
               [-1,0,0,0,0,-3.73],[0,1,2.73,3.73,1,0]])
print(SList)

[[ 0.    0.    0.    0.    0.    0.  ]
 [ 0.    1.    1.    1.    0.    0.  ]
 [ 1.    0.    0.    0.    0.    1.  ]
 [ 0.    0.    1.   -0.73  0.    0.  ]
 [-1.    0.    0.    0.    0.   -3.73]
 [ 0.    1.    2.73  3.73  1.    0.  ]]


3) Determine the Bi

In [5]:
BList=np.array([[0,0,0,0,0,0],[0,1,1,1,0,0],[1,0,0,0,0,1],[0,2.73,3.73,2,0,0],[2.73,0,0,0,0,0],[0,-2.73,-1,0,1,0]])
print(BList)

[[ 0.    0.    0.    0.    0.    0.  ]
 [ 0.    1.    1.    1.    0.    0.  ]
 [ 1.    0.    0.    0.    0.    1.  ]
 [ 0.    2.73  3.73  2.    0.    0.  ]
 [ 2.73  0.    0.    0.    0.    0.  ]
 [ 0.   -2.73 -1.    0.    1.    0.  ]]


4) Calculate T0 with SList

In [6]:
theta=np.array([-pi/2,pi/2,pi/3,-pi/4,1,pi/6])
theta=np.round(theta, 2)
print(theta)

[-1.57  1.57  1.05 -0.79  1.    0.52]


In [7]:
T0=mr.FKinSpace(M,SList,theta)
T0=np.round(T0, 2)
print(T0)

[[ 0.5   0.87  0.    1.  ]
 [ 0.22 -0.13 -0.97 -1.9 ]
 [-0.84  0.48 -0.26 -4.5 ]
 [ 0.    0.    0.    1.  ]]


5) Calculate T0 with BList

In [8]:
T0=mr.FKinBody(M,BList,theta)
T0=np.round(T0,2)
print(T0)

[[ 0.5   0.87  0.    1.  ]
 [ 0.22 -0.13 -0.97 -1.9 ]
 [-0.84  0.48 -0.26 -4.5 ]
 [ 0.    0.    0.    1.  ]]
