In [1]:
import math
import numpy as np
import modern_robotics as mr
pi=math.pi

1.

<img src='img/Img1.png'>

**Consider an iron dumbbell consisting of a cylinder connecting two solid spheres at either end of the cylinder.  The  density of the dumbbell is 5600 kg/m^3. The cylinder has a diameter of 4 cm and a length of 20 cm.  Each sphere has a diameter of 20 cm. Find the approximate rotational inertia matrix $\mathcal{I}_b$ in a frame {b} at the center of mass with z-axis aligned with the length of the dumbbell. Your entries should be written in units of kg-m^2.**

**ANSWER**

**MASS MOMENT OF INERTIA OF CYLINDER**

<center>
    $I_{xx}=I_{yy}=\frac{m(3r^2+h^2)}{12}$<br><br>
    $I_{zz}=\frac{mr^2}{2}$
</center>

In [2]:
#CYLINDER
#Calculate the Volume of the Cylinder
density=5600
radius_cylinder=0.02
length_cylinder=0.2
Volume_cylinder=pi*length_cylinder*radius_cylinder**2
print("The Cylinder's Volume is ",Volume_cylinder)
print()

#Calculate the Mass of the Cylinder
mass_cylinder=density*Volume_cylinder
print("The Cylinder's Mass is ", mass_cylinder)
print()

#Mass Moment of Inertia
Ixx_cylinder=mass_cylinder*(3*radius_cylinder**2+length_cylinder**2)/12
Iyy_cylinder=Ixx_cylinder
Izz_cylinder=mass_cylinder*radius_cylinder**2/2


IbMatrix_cylinder=np.diag([Ixx_cylinder,Iyy_cylinder,Izz_cylinder])
print("Inertia Matrix: \n {}".format(IbMatrix_cylinder))

The Cylinder's Volume is  0.0002513274122871835

The Cylinder's Mass is  1.4074335088082275

Inertia Matrix: 
 [[0.00483219 0.         0.        ]
 [0.         0.00483219 0.        ]
 [0.         0.         0.00028149]]


**MASS MOMENT OF INERTIA OF SPHERE**

<center>
    $I_{xx}=I_{yy}=I_{zz}=\frac{2Mr^2}{5}$
</center>

In [3]:
#SPHERE
#Calculate the Volume of the Sphere
radius_sphere=0.1
Volume_sphere=(4*pi*radius_sphere**3)/3
print("The Sphere's Volume is ",Volume_sphere)
print()

#Calculate the Mass of the Sphere 
mass_sphere=Volume_sphere*density
print("The Sphere's Mass is ",mass_sphere)
print()

#Mass Moment of Inertia
Ixx_sphere=mass_sphere*2/5*radius_sphere**2
Iyy_sphere=Ixx_sphere
Izz_sphere=Ixx_sphere
IbMatrix_sphere=np.diag([Ixx_sphere,Iyy_sphere,Izz_sphere])
print("Inertia Matrix: \n{}".format(IbMatrix_sphere))

The Sphere's Volume is  0.004188790204786391

The Sphere's Mass is  23.457225146803793

Inertia Matrix: 
[[0.0938289 0.        0.       ]
 [0.        0.0938289 0.       ]
 [0.        0.        0.0938289]]


In [4]:
##Steiner's Theorem
q1=np.array([[0],[0],[radius_sphere+length_cylinder/2]])
q2=np.array([[0],[0],[-radius_sphere-length_cylinder/2]])
IqMatrix_sph1=IbMatrix_sphere+mass_sphere*(np.dot(q1.T,q1)*np.eye(3)-np.dot(q1,q1.T))
IqMatrix_sph2=IbMatrix_sphere+mass_sphere*(np.dot(q2.T,q2)*np.eye(3)-np.dot(q2,q2.T))
print("Sphere_1 Ib Matrix:\n ", np.array2string(IqMatrix_sph1, separator=','))
print("\nSphere_2 Ib Matrix:\n ", np.array2string(IqMatrix_sph2, separator=','))

IMatrix_q=IbMatrix_cylinder+IqMatrix_sph1+IqMatrix_sph2
print()
print(IMatrix_q)

Sphere_1 Ib Matrix:
  [[1.03211791,0.        ,0.        ],
 [0.        ,1.03211791,0.        ],
 [0.        ,0.        ,0.0938289 ]]

Sphere_2 Ib Matrix:
  [[1.03211791,0.        ,0.        ],
 [0.        ,1.03211791,0.        ],
 [0.        ,0.        ,0.0938289 ]]

[[2.069068   0.         0.        ]
 [0.         2.069068   0.        ]
 [0.         0.         0.18793929]]


<strong>2. The equations of motion for a particular 2R robot arm can be written $M(\theta)\ddot{\theta}+c(\theta,\dot{\theta})+g(\theta)=\tau$. The Lagrangian $\mathcal{L}(\theta,\dot{\theta})$ for the robot can be written in components as:</strong><br><br>
$\mathcal{L}(\theta,\dot{\theta})=\mathcal{L}^1(\theta,\dot{\theta})+\mathcal{L}^2(\theta,\dot{\theta})+\mathcal{L}^3(\theta,\dot{\theta})+...$<br><br>
<strong>One of these components is $\mathcal{L}^1=m\dot{\theta_1}\dot{\theta_2}\sin{\theta_2}$. What's the right expression for the component of the joint torque $\tau_1^1$ at joint 1 corresponding to the component $\mathcal{L}^1$</strong>

**ANSWER**
<center> $\tau_1^1=m\ddot{\theta_2}\sin{\theta_2}+m\dot{\theta_2^2}\cos{\theta_2}$</center>

**3. Refering to the previous question, find the right expression for the component of joint torque $\tau_2^1$ at joint 2 correspondig to the component $\mathcal{L}^1$**

**ANSWER**
<center>$\tau_2^1=m\ddot{\theta_1}\sin{\theta_2}$</center>

<strong>4. For a given configuration $\theta$ of a two-joint robot, the mass matrix is:</strong>
<br><br>

$M(\theta)=\begin{vmatrix} 3 & a \\ b & 12 \end{vmatrix}$<br><br>

<strong>which has a determinant of 36-ab and eigenvalues $\frac{1}{2}(15\pm \sqrt{81+4ab})$. What constraints must a and b satisfy for this to be a valid mass matrix?</strong>

**ANSWER** 
<br><br>
- a<6
- a=b

**5. An inexact model of the UR5 mass and kinematic properties is given below:**

In [5]:
M01=np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0.089159],[0,0,0,1]])
M12=np.array([[0,0,1,0.28],[0,1,0,0.13585],[-1,0,0,0],[0,0,0,1]])
M23=np.array([[1,0,0,0],[0,1,0,-0.1197],[0,0,1,0.395],[0,0,0,1]])
M34=np.array([[0,0,1,0],[0,1,0,0],[-1,0,0,0.14225],[0,0,0,1]])
M45=np.array([[1,0,0,0],[0,1,0,0.093],[0,0,1,0],[0,0,0,1]])
M56=np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0.09465],[0,0,0,1]])
M67=np.array([[1,0,0,0],[0,0,1,0.0823],[0,-1,0,0],[0,0,0,1]])
MList=np.array([M01,M12,M23,M34,M45,M56,M67])
print("M01:\n{}\n\nM12:\n{}\n\nM23:\n{}\n\nM34:\n{}\n\nM45:\n{}\n\nM56:\n{}\n\nM67:\n{}\n"
      .format(M01,M12,M23,M34,M45,M56,M67))

M01:
[[1.       0.       0.       0.      ]
 [0.       1.       0.       0.      ]
 [0.       0.       1.       0.089159]
 [0.       0.       0.       1.      ]]

M12:
[[ 0.       0.       1.       0.28   ]
 [ 0.       1.       0.       0.13585]
 [-1.       0.       0.       0.     ]
 [ 0.       0.       0.       1.     ]]

M23:
[[ 1.      0.      0.      0.    ]
 [ 0.      1.      0.     -0.1197]
 [ 0.      0.      1.      0.395 ]
 [ 0.      0.      0.      1.    ]]

M34:
[[ 0.       0.       1.       0.     ]
 [ 0.       1.       0.       0.     ]
 [-1.       0.       0.       0.14225]
 [ 0.       0.       0.       1.     ]]

M45:
[[1.    0.    0.    0.   ]
 [0.    1.    0.    0.093]
 [0.    0.    1.    0.   ]
 [0.    0.    0.    1.   ]]

M56:
[[1.      0.      0.      0.     ]
 [0.      1.      0.      0.     ]
 [0.      0.      1.      0.09465]
 [0.      0.      0.      1.     ]]

M67:
[[ 1.      0.      0.      0.    ]
 [ 0.      0.      1.      0.0823]
 [ 0.     -1.      0.      

In [6]:
G1=np.diag([0.010267495893,0.010267495893,0.00666,3.7,3.7,3.7])
G2=np.diag([0.22689067591,0.22689067591,0.0151074,8.393,8.393,8.393])
G3=np.diag([0.049443313556,0.049443313556,0.004095,2.275,2.275,2.275])
G4=np.diag([0.111172755531,0.111172755531,0.21942,1.219,1.219,1.219])
G5=np.diag([0.111172755531,0.111172755531,0.21942,1.219,1.219,1.219])
G6=np.diag([0.0171364731454,0.0171364731454,0.033822,0.1879,0.1879,0.1879])

GList=np.array([G1,G2,G3,G4,G5,G6])
print("G1:\n{}\n\nG2:\n{}\n\nG3:\n{}\n\nG4:\n{}\n\nG5:\n{}\n\nG6:\n{}".format(G1,G2,G3,G4,G5,G6))

G1:
[[0.0102675 0.        0.        0.        0.        0.       ]
 [0.        0.0102675 0.        0.        0.        0.       ]
 [0.        0.        0.00666   0.        0.        0.       ]
 [0.        0.        0.        3.7       0.        0.       ]
 [0.        0.        0.        0.        3.7       0.       ]
 [0.        0.        0.        0.        0.        3.7      ]]

G2:
[[0.22689068 0.         0.         0.         0.         0.        ]
 [0.         0.22689068 0.         0.         0.         0.        ]
 [0.         0.         0.0151074  0.         0.         0.        ]
 [0.         0.         0.         8.393      0.         0.        ]
 [0.         0.         0.         0.         8.393      0.        ]
 [0.         0.         0.         0.         0.         8.393     ]]

G3:
[[0.04944331 0.         0.         0.         0.         0.        ]
 [0.         0.04944331 0.         0.         0.         0.        ]
 [0.         0.         0.004095   0.         0.      

In [7]:
SList=np.array([[0,0,0,0,0,0],
                [0,1,1,1,0,1],
                [1,0,0,0,-1,0],
                [0,-0.089159, -0.089159,-0.089159, -0.10915, 0.005491],
                [0,0,0,0,0.81725,0],
                [0,0,0.425,0.81725,0,0.81725]])

print("SList: \n{}".format(SList))

SList: 
[[ 0.        0.        0.        0.        0.        0.      ]
 [ 0.        1.        1.        1.        0.        1.      ]
 [ 1.        0.        0.        0.       -1.        0.      ]
 [ 0.       -0.089159 -0.089159 -0.089159 -0.10915   0.005491]
 [ 0.        0.        0.        0.        0.81725   0.      ]
 [ 0.        0.        0.425     0.81725   0.        0.81725 ]]


**ANSWER**

In [8]:
thetalist=np.array([0,pi/6,pi/4,pi/3,pi/2,2*pi/3])
dthetalist=np.array([0.2,0.2,0.2,0.2,0.2,0.2])
ddthetalist=np.array([0.1,0.1,0.1,0.1,0.1,0.1])

g=np.array([0,0,-9.81])

Ftip=np.array([0.1,0.1,0.1,0.1,0.1,0.1])

Torques=mr.InverseDynamics(thetalist,dthetalist,ddthetalist,g,Ftip,MList,GList,SList)
Torques=np.around(Torques,decimals=3)

print('Torques:\n', np.array2string(Torques,separator=','))

Torques:
 [ 1.3000e-02,-4.1148e+01,-3.7810e+00, 3.2000e-02, 3.7000e-02, 1.0300e-01]
