In [1]:
import math
import numpy as np
import modern_robotics as mr
pi=math.pi

**1. A robot system (UR5) is defined as:**

In [2]:
M01=np.array([[1, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0.089159],
              [0, 0, 0, 1]])

M12=np.array([[0,0,1,0.28],
              [0,1,0,0.13585],
              [-1,0,0,0],
              [0,0,0,1]])

M23=np.array([[1,0,0,0],
              [0,1,0,-0.1197],
              [0,0,1,0.395],
              [0,0,0,1]])

M34=np.array([[0,0,1,0],
              [0,1,0,0],
              [-1,0,0,0.14225],
              [0,0,0,1]])

M45=np.array([[1,0,0,0],
              [0,1,0,0.093],
              [0,0,1,0],
              [0,0,0,1]])

M56=np.array([[1,0,0,0],
              [0,1,0,0],
              [0,0,1,0.09465],
              [0,0,0,1]])

M67=np.array([[1,0,0,0],
              [0,0,1,0.0823],
              [0,-1,0,0],
              [0,0,0,1]])

Mlist=np.array([M01, M12, M23, M34, M45, M56, M67])

print('M01:\n{}\n\nM12:\n{}\n\nM23:\n{}\n\nM34:\n{}\n\nM45:\n{}\n\nM56:\n{}\n\nM67:\n{}'
      .format(M01,M12,M23,M34,M45,M56,M67))

M01:
[[1.       0.       0.       0.      ]
 [0.       1.       0.       0.      ]
 [0.       0.       1.       0.089159]
 [0.       0.       0.       1.      ]]

M12:
[[ 0.       0.       1.       0.28   ]
 [ 0.       1.       0.       0.13585]
 [-1.       0.       0.       0.     ]
 [ 0.       0.       0.       1.     ]]

M23:
[[ 1.      0.      0.      0.    ]
 [ 0.      1.      0.     -0.1197]
 [ 0.      0.      1.      0.395 ]
 [ 0.      0.      0.      1.    ]]

M34:
[[ 0.       0.       1.       0.     ]
 [ 0.       1.       0.       0.     ]
 [-1.       0.       0.       0.14225]
 [ 0.       0.       0.       1.     ]]

M45:
[[1.    0.    0.    0.   ]
 [0.    1.    0.    0.093]
 [0.    0.    1.    0.   ]
 [0.    0.    0.    1.   ]]

M56:
[[1.      0.      0.      0.     ]
 [0.      1.      0.      0.     ]
 [0.      0.      1.      0.09465]
 [0.      0.      0.      1.     ]]

M67:
[[ 1.      0.      0.      0.    ]
 [ 0.      0.      1.      0.0823]
 [ 0.     -1.      0.      

In [3]:
G1=np.diag([0.01026749,0.01026749,0.00666,3.7,3.7,3.7])
G2=np.diag([0.22689,0.22689,0.0151074,8.393,8.393,8.393])
G3=np.diag([0.0494433,0.0494433,0.004095,2.275,2.275,2.275])
G4=np.diag([0.1111727,0.1111727,0.21942,1.219,1.219,1.219])
G5=np.diag([0.1111727,0.1111727,0.21942,1.219,1.219,1.219])
G6=np.diag([0.017136,0.017136,0.033822,0.1879,0.1879,0.1879])
Glist = np.array([G1, G2, G3, G4, G5, G6])

print('Spatial Inertia Matrix of Link 1: \n', G1)
print('\nSpatial Inertia Matrix of Link 2: \n', G2)
print('\nSpatial Inertia Matrix of Link 3: \n', G3)
print('\nSpatial Inertia Matrix of Link 4: \n', G4)
print('\nSpatial Inertia Matrix of Link 5: \n', G5)
print('\nSpatial Inertia Matrix of Link 6: \n', G6)

Spatial Inertia Matrix of Link 1: 
 [[0.01026749 0.         0.         0.         0.         0.        ]
 [0.         0.01026749 0.         0.         0.         0.        ]
 [0.         0.         0.00666    0.         0.         0.        ]
 [0.         0.         0.         3.7        0.         0.        ]
 [0.         0.         0.         0.         3.7        0.        ]
 [0.         0.         0.         0.         0.         3.7       ]]

Spatial Inertia Matrix of Link 2: 
 [[0.22689   0.        0.        0.        0.        0.       ]
 [0.        0.22689   0.        0.        0.        0.       ]
 [0.        0.        0.0151074 0.        0.        0.       ]
 [0.        0.        0.        8.393     0.        0.       ]
 [0.        0.        0.        0.        8.393     0.       ]
 [0.        0.        0.        0.        0.        8.393    ]]

Spatial Inertia Matrix of Link 3: 
 [[0.0494433 0.        0.        0.        0.        0.       ]
 [0.        0.0494433 0.        0

In [4]:
SList=np.array([[0,0,0,0,0,0],
                [0,1,1,1,0,1],
                [1,0,0,0,-1,0],
                [0,-0.089159,-0.089159,-0.089159,-0.10915,0.005491],
                [0,0,0,0,0.81725,0],
                [0,0,0.425,0.81725,0,0.81725]])

print('Screw axes of the Joints: \n',SList)

Screw axes of the Joints: 
 [[ 0.        0.        0.        0.        0.        0.      ]
 [ 0.        1.        1.        1.        0.        1.      ]
 [ 1.        0.        0.        0.       -1.        0.      ]
 [ 0.       -0.089159 -0.089159 -0.089159 -0.10915   0.005491]
 [ 0.        0.        0.        0.        0.81725   0.      ]
 [ 0.        0.        0.425     0.81725   0.        0.81725 ]]


In [5]:
thetalist=np.array([0,pi/6,pi/4,pi/3,pi/2,2*pi/3])
dthetalist=np.array([0.2,0.2,0.2,0.2,0.2,0.2])
ddthetalist=np.array([0.1,0.1,0.1,0.1,0.1,0.1])
g=np.array([0,0,-9.81])
Ftip=np.array([0.1,0.1,0.1,0.1,0.1,0.1])

print("Given:")
print('Joint positions: \n',thetalist)
print('\nJoint velocities: \n',dthetalist)
print('\nJoint accelerations: \n',ddthetalist)
print('\nGravity Vector: \n', g)
print('\nSpatial force applied by the end-effector: \n', Ftip)

Given:
Joint positions: 
 [0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951 ]

Joint velocities: 
 [0.2 0.2 0.2 0.2 0.2 0.2]

Joint accelerations: 
 [0.1 0.1 0.1 0.1 0.1 0.1]

Gravity Vector: 
 [ 0.    0.   -9.81]

Spatial force applied by the end-effector: 
 [0.1 0.1 0.1 0.1 0.1 0.1]


**Calculate the Inertia Matrix**

In [6]:
#Calculate the Mass M(theta)

M=mr.MassMatrix(thetalist,Mlist,Glist,SList)
M=np.around(M,decimals=3)
print("Mass Matrix of the UR5 open-chain robot: \n",M)

Mass Matrix of the UR5 open-chain robot: 
 [[ 2.198  0.272  0.068 -0.006  0.17  -0.012]
 [ 0.272  3.554  1.31   0.24  -0.007  0.   ]
 [ 0.068  1.31   0.837  0.248 -0.007  0.   ]
 [-0.006  0.24   0.248  0.254 -0.007  0.   ]
 [ 0.17  -0.007 -0.007 -0.007  0.241  0.   ]
 [-0.012  0.     0.     0.     0.     0.017]]


**2. Calculate the Coriolis and Centripetal Terms**

In [7]:
#Calculate h(theta,dot{theta})

C=mr.VelQuadraticForces(thetalist,dthetalist,Mlist,Glist,SList)
C=np.around(C,decimals=3)
print('Coriolis and Centripetal Terms: \n',C)

Coriolis and Centripetal Terms: 
 [-0.117 -0.011  0.032 -0.015  0.023  0.003]


**3. Calculate the joint forces/torques required to overcome gravity.**

In [8]:
#Calculate gravity constraints

G=mr.GravityForces(thetalist,g,Mlist,Glist,SList)
G=np.around(G,decimals=3)
print('Joint Forces/Torques the robot requires to overcome gravity at its configuration: \n',G)

Joint Forces/Torques the robot requires to overcome gravity at its configuration: 
 [  0.    -41.597  -3.936   0.123   0.      0.   ]


**4. Calculate the joint forces/torques required to generate the wrench $\mathcal{F}_{tip}$**

In [9]:
#Calculate the force needed to create Ftip

EEF=mr.EndEffectorForces(thetalist,Ftip,Mlist,Glist,SList)
EEF=np.around(EEF,decimals=3)
print('Joint Forces/Torques the robot requires to create the end-effector force Ftip: \n',EEF)

Joint Forces/Torques the robot requires to create the end-effector force Ftip: 
 [-0.139 -0.077 -0.122 -0.149 -0.025  0.1  ]


**5. For the same robot system and condition plus the known joint forces/torques**

In [10]:
taulist=np.array([0.0128,-41.1477,-3.7809,0.0323,0.037,0.1034])

print('Tau:\n{}'.format(np.round(taulist, decimals=3)))

Tau:
[ 1.3000e-02 -4.1148e+01 -3.7810e+00  3.2000e-02  3.7000e-02  1.0300e-01]


**Find the joint acceleration.**

In [11]:
FD=mr.ForwardDynamics(thetalist,dthetalist,taulist,g,Ftip,Mlist,Glist,SList)
FD=np.around(FD,decimals=3)
print('Forward Dynamics in the Space Frame: \n',FD)

Forward Dynamics in the Space Frame: 
 [0.1   0.1   0.1   0.1   0.1   0.102]


**6. Assume that the inertia of a revolute motor's robot about its central axis is $0.005kg*m^2$. The motor is attached to a zero-inertia 200:1 gearhead if you grab the gearhead output and spin it by hand, what is the inertia you feel?**

**R:** 200 $kg*m^2$