# Rigid Body Motion Assignment

In [1]:
import modern_robotics as mr
import numpy as np
import math

1) In terms of the xs, ys, zs, coordinates of a fixed space frame {s}, the frame {a} has its xa=(0,0,1) and its ya=(1,0,0), and the frame {b} has its xb=(1,0,0) and its yb=(0,0,-1). Draw the {s}, {a} and {b} frames. Write the rotation matrix $R_{sa}$

In [2]:
Rs=np.array([[1,0,0],
           [0,1,0],
           [0,0,1]])

Rsa=np.array([[0,1,0],
            [0,0,1],
            [1,0,0]])

Rsb=np.array([[1,0,0],
            [0,0,1],
            [0,-1,0]])
Rbs=mr.RotInv(Rsb)

print(Rsa)

[[0 1 0]
 [0 0 1]
 [1 0 0]]


2) Write the rotation matrix $R_{bs}$.

In [3]:
print(Rbs)

[[ 1  0  0]
 [ 0  0 -1]
 [ 0  1  0]]


3) Write the rotation matrix $R_{ab}$.

In [4]:
Rab=np.dot(mr.RotInv(Rsa),Rsb)
print(Rab)

[[ 0 -1  0]
 [ 1  0  0]
 [ 0  0  1]]


4) Let R=Rsb be consider as a transformation operator consisting of a rotation about x by -90. Calculate R1=RsaR, and think of Rsa as the representation of the initial orientation {a} relative to {s}, R as a rotation operator, and R1 as the new orientation of {a} after performing rotation. The new orientation R1 correspond to the orientation of the new {a} frame relative to {s} after rotation the original {a} frame by -90 about which axis?

- The xa axis of the {a} frame

5) Use Rsb to change the representation of the point $p_b=[1,2,3]^T$ to {s} coordinates

In [5]:
Pb=np.array([[1],[2],[3]])
Ps=np.dot(Rsb,Pb)
print(Ps)

[[ 1]
 [ 3]
 [-2]]


6) Choose a point $p_s=[1,2,3]^T$ in {s} coordinates and calculate $q=R_{sb}^T P_s$. Is q a representation of P in {b} coordinates?

Yes, $q=R_{sb}^T *Ps=Pb$

In [6]:
Ps_2=np.array([[1],[2],[3]])
Pb_2=np.dot(Rbs,Ps_2)
print(Pb_2)

[[ 1]
 [-3]
 [ 2]]


7) An angular velocity "w" is represented in {s} as $w_s=[3,2,1]^T$. What is its representantion W_a?

In [7]:
Ws=np.array([[3],[2],[1]])
Wa=np.dot(mr.RotInv(Rsa), Ws)
print(Wa)

[[1]
 [3]
 [2]]


8) Calculate the matrix log $[\hat{w}]\theta$ of $R_{sa}$. Extract and enter the rotation amount $\theta$ in radians.

In [8]:
rsa=mr.MatrixLog3(Rsa)
rsa=mr.so3ToVec(rsa)
(omghat, theta)=mr.AxisAng3(rsa)
print('{}'.format(round(theta,2)))

2.09


9) Calculate the exponential matrix corresponding to the exponential coordinates $\hat{w}\theta=(1,2,0)^T$

In [9]:
wO=np.array([[1],[2],[0]])
wO=mr.VecToso3(wO)
R=mr.MatrixExp3(wO)
print(R)

[[array([-0.2938183]) array([0.64690915]) array([0.70368982])]
 [array([0.64690915]) array([0.67654542]) array([-0.35184491])]
 [array([-0.70368982]) array([0.35184491]) array([-0.61727288])]]


C:\Users\GABRIEL ALVARADO\anaconda3\envs\py3env\lib\site-packages\modern_robotics\core.py:88: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return np.array([[0,      -omg[2],  omg[1]],


10) Write the 3x3 skew-symmetric matrix correspond to $w=(1,2,0.5)^T$

In [10]:
w=np.array([[1],[2],[0.5]])
w=mr.VecToso3(w)
print(w)

[[0 array([-0.5]) array([2.])]
 [array([0.5]) 0 array([-1.])]
 [array([-2.]) array([1.]) 0]]


11) Use the function MatrixExp3 to calculate the rotation matrix $R\in SO(3)$ corresponding to the matrix exponential

In [11]:
WO=np.array([[0, 0.5,-1],[-0.5,0,2],[1,-2,0]])
r=mr.MatrixExp3(WO)
print(r)

[[ 0.60482045  0.796274   -0.01182979]
 [ 0.46830057 -0.34361048  0.81401868]
 [ 0.64411707 -0.49787504 -0.58071821]]


12) Use MatrixLog3 to calculate the matrix log $[\hat{w}]\theta \in so(3)$

In [12]:
Rin=np.array([[0,0,1],[-1,0,0],[0,-1,0]])
w0=mr.MatrixLog3(Rin)
print(w0)

[[ 0.          1.20919958  1.20919958]
 [-1.20919958  0.          1.20919958]
 [-1.20919958 -1.20919958  0.        ]]
