# Rigid Body Motions and Twist Assignment

1) In terms of the xs, ys, zs coordinates of a fixed frame {s}, the frame {a} has its xa-axis point in the direction (0,0,1) and its ya-axis in (-1,0,0), and frame {b} has its xb-axis in (1,0,0) and yb-axis in (0,0,-1). The origin of {a} is at (0,0,1) in {s} and the origin of {b} is at (0,2,0). Draw the {s}, {a} and {b} frames. Write Tsa, transpose(Tsb) and Tab.

In [3]:
import numpy as np
import modern_robotics as mr
Rs=np.array([[1,0,0],[0,1,0],[0,0,1]])
Rsa=np.array([[0,-1,0],[0,0,-1],[1,0,0]])
Rsb=np.array([[1,0,0],[0,0,1],[0,-1,0]])
Tsa=np.array([[0,-1,0,0],
             [0,0,-1,0],
             [1,0,0,1],
             [0,0,0,1]])
Tsa

array([[ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 1,  0,  0,  1],
       [ 0,  0,  0,  1]])

In [5]:
Tsb=np.array([[1,0,0,0],
             [0,0,1,2],
             [0,-1,0,0],
             [0,0,0,1]])
Tbs=mr.TransInv(Tsb)
Tbs

array([[ 1,  0,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  1,  0, -2],
       [ 0,  0,  0,  1]])

In [8]:
Tab=np.dot(mr.TransInv(Tsa),Tsb)
Tab

array([[ 0, -1,  0, -1],
       [-1,  0,  0,  0],
       [ 0,  0, -1, -2],
       [ 0,  0,  0,  1]])

2) Let T=Tsb be consider as a transformation operator consisting of a rotation about x by -90 and a translation along y by 2 units. Calculate T1=TTsa. Are the rotation axis x and translation axis y of T properly considered to be expressed in the frame {s} or {a}.

- The Frame {s}

3) Use Tsb to change the representation of the point pb=transpose(1,2,3) to {s} coordinates.

In [9]:
Pb_1=np.array([[1],[2],[3],[1]])
Ps_1=np.dot(Tsb,Pb_1)
Ps_1

array([[ 1],
       [ 5],
       [-2],
       [ 1]])

4) Choose a point ps=transpose(1,2,3) in {s} coordinates. Calculate q=TsbPs. Is q a representation of p in {b}

- No

5) A twist V is represented in {s} as Vs=transpose(3,2,1,-1,-2,-3). What is the representation Va?

In [30]:
Vs=np.array([[3],[2],[1],[-1],[-2],[-3]])
Tas=mr.TransInv(Tsa)
Va=np.dot(np.transpose(mr.Adjoint(Tsa)),Vs)
Va

array([[ 1.],
       [-1.],
       [-3.],
       [-3.],
       [ 1.],
       [ 2.]])

6) Calculate the log [S]0 of Tsa. Write "Theta"

In [21]:
S0=np.array([[0,-1.2092,-1.2092,0.7364],[1.2092,0,-1.2092,0.4728],[1.2092,1.2092,0,0.7364],[0,0,0,0]])
s0=mr.se3ToVec(S0)
s0

array([ 1.2092, -1.2092,  1.2092,  0.7364,  0.4728,  0.7364])

In [22]:
(S,Theta)=mr.AxisAng6(s0)
Theta

2.0943958365122866

7) Calculate the matrix exponential of rigid body motion S0=transpose(0,1,2,3,0,0)

In [23]:
S0=np.array([[0,-2,1,3],
            [2,0,0,0],
            [-1,0,0,0],
            [0,0,0,0]])
T=mr.MatrixExp6(S0)
T

array([[-0.61727288, -0.70368982,  0.35184491,  1.05553472],
       [ 0.70368982, -0.2938183 ,  0.64690915,  1.94072745],
       [-0.35184491,  0.64690915,  0.67654542, -0.97036373],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

8) Use Tsb the change the representation of the wrench Fb=transpose(1,0,0,2,1,0) to {s} coordinates

In [29]:
Fb=np.array([[1],[0],[0],[2],[1],[0]])
Ad_Tsb=np.transpose(mr.Adjoint(Tbs))
Fs=np.dot(Ad_Tsb,Fb)
Fs

array([[-1.],
       [ 0.],
       [-4.],
       [ 2.],
       [ 0.],
       [-1.]])

9) Transpose the Matrix 'T'

In [32]:
T=np.array([[0,-1,0,3],
           [1,0,0,0],
           [0,0,1,1],
           [0,0,0,1]])
TransT=mr.TransInv(T)
TransT

array([[ 0,  1,  0,  0],
       [-1,  0,  0,  3],
       [ 0,  0,  1, -1],
       [ 0,  0,  0,  1]])

10) Write the se(3) correspoding to V=transpose(1,0,0,0,2,3)

In [34]:
V=np.array([[1],[0],[0],[0],[2],[3]])
se3=mr.VecTose3(V)
se3

array([[0, array([0]), array([0]), 0],
       [array([0]), 0, array([-1]), 2],
       [array([0]), array([1]), 0, 3],
       [0.0, 0.0, 0.0, 0.0]], dtype=object)

11) Use ScrewToAxis to calculate the normalized screw axis representation S of the screw described by s=(1,0,0) in the direction of the screw axis, located at the point p=(0,0,2) with h=1.

In [36]:
q=np.array([0,0,2])
s=np.array([1,0,0])
h=1
S=mr.ScrewToAxis(q,s,h)
S

array([1, 0, 0, 1, 2, 0])

12) Use MatrixExp6 to calculate the homogeneous transformation matrix T E SE(3)

In [40]:
S0=np.array([[0,-1.5708,0,2.3562],
            [1.5708,0,0,-2.3562],
            [0,0,0,1],
            [0,0,0,0]])
V=mr.MatrixExp6(S0)
V

array([[-3.67320510e-06, -1.00000000e+00,  0.00000000e+00,
         3.00000551e+00],
       [ 1.00000000e+00, -3.67320510e-06,  0.00000000e+00,
         5.50981777e-06],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

13) Use MatrixLog6 on T

In [41]:
T=np.array([[0,-1,0,3],[1,0,0,0],[0,0,1,1],[0,0,0,1]])
S0=mr.MatrixLog6(T)
S0

array([[ 0.        , -1.57079633,  0.        ,  2.35619449],
       [ 1.57079633,  0.        ,  0.        , -2.35619449],
       [ 0.        ,  0.        ,  0.        ,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])